#!/bin/bash
# ansi colors for formatting heredoc
ESC=$(printf "\e")
GREEN="$ESC[0;32m"
NO_COLOR="$ESC[0;0m"
RED="$ESC[0;31m"
MAGENTA="$ESC[0;35m"
YELLOW="$ESC[0;33m"
BLUE="$ESC[0;34m"
WHITE="$ESC[0;37m"
#PURPLE="$ESC[0;35m"
CYAN="$ESC[0;36m"


function mem_used(){
    local total=$(free  | grep "Mem:" |awk '{print $2}')
    local free=$(free | grep 'Mem:' | awk '{print $4}')
    export FREE_PERCENT=$(awk 'BEGIN{printf"%.2f%\n",('$free'/'$total')*100}')
}

function loop_check_mem(){
    if [[ ${FREE_PERCENT} = "13%" ]];then
        echo ${YELLOW}Warning: The system has less than 13% of RAM free,will REBOOT now!!! ${NO_COLOR}
        reboot
    else
        echo ${GREEN} The free mem percent is: ${YELLOW}${FREE_PERCENT}${NO_COLOR}
    fi
}

###main
mem_used
while true;do
    loop_check_mem
    sleep 3
done


